### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by vennand** [pyomeca/biorbd-viz#17]
Salut,

J'essaye d'utiliser les exemples de biorbd-viz, mais je n'arrive pas à les faire rouler. Sont-ils sensés fonctionner?

3d_viz.py 

`Traceback (most recent call last):
  File "3d_viz.py", line 48, in <module>
    all_rt_real.append(RotoTrans(angles=[0, 0, 0], angle_sequence="yxz", translations=d[:, 0, 0]))
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/pyomeca/rototrans.py", line 28, in __new__
    rt = cls.rt_from_euler_angles(angles=angles, angle_sequence=angle_sequence, translations=translations)
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/pyomeca/rototrans.py", line 152, in rt_from_euler_angles
    if angles.get_num_frames() != 0 and translations.get_num_frames() == 0:
AttributeError: 'list' object has no attribute 'get_num_frames'`

biorbd_viz.py

`Traceback (most recent call last):
  File "biorbd_viz.py", line 9, in <module>
    b = BiorbdViz(model_path="pyomecaman.bioMod")
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/__init__.py", line 126, in __init__
    self.set_q(self.Q)
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/__init__.py", line 155, in set_q
    self.__set_rt_from_q()
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/__init__.py", line 518, in __set_rt_from_q
    self.vtk_model.update_rt(self.rt)
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/biorbd_vtk.py", line 818, in update_rt
    self.new_rt_set(all_rt)
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/biorbd_vtk.py", line 801, in new_rt_set
    self.update_rt(all_rt)
  File "/home/andre/anaconda3/envs/rbdl/lib/python3.7/site-packages/BiorbdViz/biorbd_vtk.py", line 833, in update_rt
    pts.InsertNextPoint(rt.translation() + rt[0:3, 0] * self.rt_length)
TypeError: InsertNextPoint argument 1: only size-1 arrays can be converted to Python scalars`

**Comment by pariterre** [comment]
Bonjour vennand!
Désolé pour ma réponse démesurément tardive! Effectivement, nous avons changé beaucoup l'API de pyomeca dernière et je n'avais pas fait attention, mais les exemples étaient broken. J'ai fait une pull request tout à l'heure, pour corriger le problème. Cependant, elle est attachée à une autre pull request que j'ai dû faire sur Pyomeca. 
Conséquemment, d'ici les exemples devraient être fonctionnels d'ici quelques jours!

Merci d'avoir pointé ces problèmes!
